### ISSUE TITLE
Updated version of FDTD module

### ISSUE THREAD

**Issue by Substancia** [flaport/fdtd#12]
Hi, 
I am a final year Masters student in Theoretical Physics at IIT Madras. When I started my final year project in August 2020, this was the best suiting cross-platform FDTD module I could find for my simulation project. In past months, I have added many features to this module to fit my purposes, like real-time simulation video, saving simulation video and detector history and grid details, Hanning window pulse sources etc. Once I wrap up my project in next two months, I would like to share my progress on your library and help the community grow.

**Comment by flaport** [comment]
Hi mohammad, that's awesome! Any future pull requests are always welcome 🙂

**Comment by Substancia** [comment]
That's awesome then! Once I wrap up my final year project, I will make a pull request and add only the stable features, which you can cross-check and let me know your verdicts!

**Comment by flaport** [comment]
Sounds good! Feel free to make PRs for unstable features too. I might merge them into a separate branch then.

**Comment by flaport** [comment]
Hey @Substancia , do you have any updates on this?

**Comment by Substancia** [comment]
Hi @flaport , I am currently wrapping up my final year project and writing the report. I expect to submit the report on May 28. I was planning to spend the following week to see through the updates. I will put up a PR sometime this week so you can see what I have done so far.

**Comment by flaport** [comment]
Thanks, @Substancia :)

**Comment by flaport** [comment]
This was closed by PR #15. Some slight modifications to the additions were made in later commits. Additionally, the example python files were converted into Jupyter notebooks to be able to render them for the documentation [here](https://fdtd.readthedocs.io/en/latest/examples/05-lenses-and-analysing-lensing-actions.html) and [here](https://fdtd.readthedocs.io/en/latest/examples/06-GRIN-medium-and-analysing-refraction.html).
