### ISSUE TITLE
Acoustic simulations?

### ISSUE THREAD

**Issue by sofroniewn** [flaport/fdtd#17]
Hello, I know this package is for 3D electromagnetic simulations, but I was wondering what it would take for it to also be used for acoustic simulations (including in situations where the speed of sound was not constant). Would this be something of interest to you, or is it too far outside the scope of this package? My [elementary reading](https://eecs.wsu.edu/~schneidj/ufdtd/chap12.pdf) suggests that it shouldn't be too hard to have equations also for sound propagation work in this framework, but curious what you think.

**Comment by flaport** [comment]
Hey @sofroniewn, although it seems that should be a 1 to 1 mapping (at least in 2D), I don't consider myself to be an acoustics expert at all. Therefore, I cannot confidently implement and maintain this. I think the best way to handle acoustics with this framework would be to indeed find relations like (12.35)-(12.46) for 3D and use those as a 'translation layer' for this package, however I'm afraid I won't be of much more help than the reference you just linked to (which btw was used as a rough guide to make this library).

**Comment by sofroniewn** [comment]
Ok thanks for the consideration, that all makes sense. I might try the acoustic simulation in a fork of this repo when I find the time!!

**Comment by flaport** [comment]
Sounds good! Let me know if you get it working 🙂
