### ISSUE TITLE
Flat Plane Source

### ISSUE THREAD

**Issue by CharlesDove** [flaport/fdtd#24]
Hi folks, thanks for the awesome fdtd package! 
I'm trying to get a flat PlaneSource, eg a flat plane on z=N, but I haven't found a way to do it. Using something like `grid[:,:,5]=fdtd.AnisotropicObject(permittivity=permittivity)` gives a diagonal plane. Is there a way to get a flat plane? Thanks!

**Comment by flaport** [comment]
Hey @CharlesDove , this is indeed a bug, thanks for noticing!

What I suspect is going on is that the `PlaneSource` is actually correctly created, but the `grid.visualize` function does not know how to visualize it. I'll try adding this to the visualization function`.

**Comment by CharlesDove** [comment]
That makes sense, thanks!
