### ISSUE TITLE
Unit of conductivity

### ISSUE THREAD

**Issue by chenyang9526** [flaport/fdtd#28]
Hi @flaport, thanks for the excellent toolbox. Just a quick question, may I know the unit of conductivity defined in the absorbing object? 
In your example (https://fdtd.readthedocs.io/en/latest/examples/02-absorbing-object.html#), the conductivity was set to 1e-6, but the unit was not provided. 
I'm interested in a medium that has a conductivity of 0.6 ohm-1 m-1. However, if I set the conductivity to 0.6, the program gives a absorption_factor larger than 1. Could you give me any suggestions on setting the correct conductivity for your toolbox. Thanks!

**Comment by flaport** [comment]
Hi @chenyang9526 , the simulation unit for the conductivity in the `AbsorbingObject` is `s-1`. To obtain the simulation units from the physical units, divide by `εε0`:

```
σ_sim = σ_phys / (ε ε0)
```

Read more about this [here](https://github.com/flaport/fdtd#lossy-medium).
