### ISSUE TITLE
Defining conductivity tensor raises error

### ISSUE THREAD

**Issue by pingpongballz** [flaport/fdtd#36]
Hi, 

First of all, Thank you for this amazing module!

The issue right now is by defining an absorbing object with a permittivity matrix, perm and a conductivity matrix, cond in a 2D simulation, the code raises an error: 

`self.grid.E[loc] *= (1 - self.absorption_factor) / (1 + self.absorption_factor)`
`ValueError: non-broadcastable output operand with shape (64,64,1,3) doesn't match the broadcast shape (64,64,64,3)`

   `perm = np.array([[[item[0]] for item in row] for row in matrix])`
    `cond = np.array([[[item[1]] for item in row] for row in matrix])`
    `grid[10:74, 10:74, 0] = fdtd.AbsorbingObject(permittivity=mask, conductivity = cond, name="object")`

Matrix is a 64 by 64 by 2 array containing the permittivity and conductivity at each voxel.

In the code, I'm defining a matrix which will contain the permittivity and conductivity tensor, each with a different value. Removing the conductivity tensor fixes the issue, however and the module works as expected.

Any advice to fix this would be appreciated.

**Comment by flaport** [comment]
Hi @pingpongballz ,

It seems like you're adding a 3D array (64, 64, 64, 3) to a 2D grid (64, 64, 1, 3).

It would be useful if you could share a minimal example that produces this problem, so I can check if it's a bug or something you're doing wrong ;-)

**Comment by flaport** [comment]
This was solved in fdtd version 0.2.1.
