### ISSUE TITLE
Question regarding conductivity implementation in code

### ISSUE THREAD

**Issue by pingpongballz** [flaport/fdtd#37]
Hi, 

I was browsing through `objects.py` when I came upon this, lines 192-199,

```python
 self.absorption_factor = (
            0.5
            * self.grid.courant_number
            * self.inverse_permittivity
            * self.conductivity
            * self.grid.grid_spacing
            / const.eps0
        )
```
which is `f = 0.5*sc*inv(ε)*σe*du/ε0`
In [https://github.com/flaport/fdtd#lossy-medium](url), the following is written:
```python
f = 0.5*dt*σ, where σ := inv(ε)*σe/ε0
```
by taking `dt = sc * du/c` I can expand `f = (0.5*sc*inv(ε)*σe*du)/(ε0*c)`

My question is, why wasn't 1/speed of light, `1/c` included in ` self.absorption_factor` ?  There must be something I'm missing, right? 

Any clarification to my confusion would be most appreciated 😄

**Comment by flaport** [comment]
Hi @pingpongballz ,

My apologies for my very late answer. I wanted to re-derive the equations and then forgot about this issue. It seems you are indeed correct! There is a 1/c value missing. I have updated the code and the README.
