### ISSUE TITLE
Float128 not supported on Windows

### ISSUE THREAD

**Issue by Julius-Py** [flaport/fdtd#39]
I recently installed this on Windows and I'm using Jupyter notebook, It seems to not support the float 128, any thoughts?

AttributeError: module 'numpy' has no attribute 'float128'

**Comment by flaport** [comment]
Hi @Julius-Py ,

FDTD just uses numpy/pytorch dtypes. It depends on which platform you are on which dtypes are available. There is not much I can do to change this I'm afraid...

**Comment by pingpongballz** [comment]
Hi @flaport,

I think what @Julius-Py meant was that having numpy.float128 as a dtype in backend.py in windows just causes the fdtd module to fail to initialize, and subsequently returning an error:
 ``AttributeError: module 'numpy' has no attribute 'float128'``

@Julius-Py, I did a quickfix by just removing any references to numpy.float128 in backend.py and it seemed to do the trick

**Comment by flaport** [comment]
That's indeed a fair point. I've pushed a fix and this issue will be solved in fdtd>=0.2.4
