### ISSUE TITLE
Value of eps0, mu0 in constants.py

### ISSUE THREAD

**Issue by AaronParsons** [flaport/fdtd#41]
Line 17 of constants.py assigns eps0 = 4e-7 * pi, but isn't this the value of mu0? See https://en.wikipedia.org/wiki/Vacuum_permittivity

**Comment by flaport** [comment]
Hi @AaronParsons ,

You are correct! I added constants.py two commits ago and I must have swapped them around when defining the file. Pretty emberassing... Luckily I had not made a new release yet.

Anyway. Closing now as the issue has been resolved. Thanks a lot for finding this!
