### ISSUE TITLE
Can I simulate birefringent material (eg. liquid crystal) with this simulation?

### ISSUE THREAD

**Issue by bellzero5** [flaport/fdtd#44]
Hi! Thank you for this wonderful project.
Can I simulate birefringent material (eg. liquid crystal) with this simulation?
Thank you.

**Comment by flaport** [comment]
yes you can. 

unixial or biaxial materials can easily be modeled by setting `grid.inverse_permittivity` directly.

If you need off-axis elements in your permittivity, you'll need to create a custom `Object`. You can have a look at how `AnisotropicObject` is implemented and do something similar (or subclass it).

Good luck 🙂
