### ISSUE TITLE
Unit correction 

### ISSUE THREAD

**Issue by QizhouW** [flaport/fdtd#46]
I found this issue in the doc.
'A grid_spacing can be given. For stability reasons, it is recommended to choose a grid spacing that is at least 10 times smaller than the smallest wavelength in the grid. This means that for a grid containing a source with wavelength 1550nm and a material with refractive index of 3.1, the recommended minimum grid_spacing turns out to be 50pm'

This 50 pm seems to be wrong, instead, it should be 50 nm.

**Comment by flaport** [comment]
Thanks for catching that one @QizhouW. It should now be fixed.
