### ISSUE TITLE
example.py not compiling

### ISSUE THREAD

**Issue by shudras** [flaport/fdtd#5]
_AttributeError: module 'fdtd' has no attribute 'Detectors'_

changing _fdtd.Detectors_ to _fdtd.LineDetector_ seems to solve the problem but raises another problem: 

_ValueError: at least one projection plane (x, y or z) should be supplied to visualize the grid!_

**Comment by flaport** [comment]
Hey, thanks for bringing that up! I fixed these bugs and the example script should run again now.
