### ISSUE TITLE
Loading Spatial Distributions

### ISSUE THREAD

**Issue by kwadwo00** [flaport/fdtd#56]
When loading an array into the "permittivity" parameter, I get the following error:

TypeError: only size-1 arrays can be converted to Python scalars

from "...\fdtd\grid.py" line 159

I believe this is because it's trying to apply "float()" to a numpy array. Changing this to "bd.float()" appears to fix it for numpy, but I don't know if it is compatible with the others.

Just putting it on your radar.

Cheers!

**Comment by flaport** [comment]
Thanks for catching that! Fixed in version 0.2.6.
