### ISSUE TITLE
new grid permittivity strategy & issues with PML and Objects

### ISSUE THREAD

**Issue by tlambert03** [flaport/fdtd#6]
I fear I may have caused more problems in issue #4.  It appears that commit 3e22a26 has introduced some new bugs relating to PMLs and certain objects.  (either that or I'm using them incorrectly, and this commit exposed my errors)

To explain the issue, let me describe my simulation.  I have a simply "TIR" example grid where the top half has a higher refractive index (1.55) than the bottom (1.33), an angled `LineSource` points at the middle of the grid, and a (somewhat strange) very high refractive index "absorbing" object serves to block stray energy on the left side at the interface, and PMLs surround the grid (note: the 1.55 RI region overlaps the PML):

<img width="435" alt="grid layout" src="https://user-images.githubusercontent.com/1609449/66760914-ff63f700-ee70-11e9-879f-e29437c506b6.png">

previously, this was the result after running for a while:
<img width="628" alt="old_version" src="https://user-images.githubusercontent.com/1609449/66761167-739e9a80-ee71-11e9-94c2-fa631616db2c.png">

[these lines](https://github.com/flaport/fdtd/blob/3e22a26e433240db886adaee2577817304ca07de/fdtd/objects.py#L61-L76) in commit 3e22a26 now cause some strange (high magnitude E-field) results in both the PML and my weird high refractive index object at the interface:
<img width="638" alt="new version" src="https://user-images.githubusercontent.com/1609449/66761538-3981c880-ee72-11e9-8a43-e84d1c9c9f91.png">

I can remove the boundary errors by taking extra care not to have any objects overlapping the PML regions, (though previously, fdtd handled this a bit more gracefully, and it didn't matter whether these overlapped).  However, I still have problems with my "absorbing" object at the interface.
<img width="630" alt="new_without_overriding_pml" src="https://user-images.githubusercontent.com/1609449/66761657-70f07500-ee72-11e9-911f-6b8a4055b2b0.png">

it's possible that I'm just not implementing absorbing objects correctly, or that the object edge code just needs some tweaks ... but it also seems like there are generally more "gotchas" now with the new grid permittivity strategy and the PML than there were before you generously dealt with my request to remove objects :)

I tried for a while to figure out a PR to fix it gracefully while leaving the ability to remove objects, but so far have failed.  I personally wouldn't mind if you wanted to rollback the grid removal idea for a while, if it's the easiest way to deal with this.  I know you're busy with other things!

thanks again!

**Comment by flaport** [comment]
The previous commit was rolled back. Thanks for noticing! I'll see if I can find a better solution in the near future. Also, the library clearly needs some tests (#7) to prevent these unexpected bugs in the future.

I haven't figured out what exactly caused this numerical instability, so I'll leave this issue open until either I find the problem or find a better way of implementing the removal of the objects.

**Comment by flaport** [comment]
My preferred test runner is pytest. I created some sample test cases, feel free to add some more. Read #7 for some guidelines and discussion about tests. 
I'm closing this issue for now since I most likely won't go back to the solution (#6) initially proposed in #4, which solves this issue. The object removal discussion can be had there.
