### ISSUE TITLE
development dependencies not downloading

### ISSUE THREAD

**Issue by KyrellosIbrahim** [flaport/fdtd#64]
I installed most of the requirements through terminal, however when i go to do the command"pip install -e fdtd[dev]" it gives me the message saying "zsh: no matches found: fdtd[dev]". I have an M2 macbook air and am running python 3.10.9. Is there any way i can work around this issue?

**Comment by flaport** [comment]
on zsh the `[` and `]` need to be escaped. Try

```
pip install fdtd\[dev\]
```

or alternatively you can also quite it
```
pip install "fdtd[dev]"
```

**Comment by flaport** [comment]
closing this for now
