### ISSUE TITLE
Where to obtain Total field Array

### ISSUE THREAD

**Issue by akrabawi** [flaport/fdtd#67]
The total field array is _E which has the dimensions [Nx, Ny, Nz, 3] with
Ex = [:, :, :, 0]
Ey = [:, :, :, 1]
Ez = [:, :, :, 2]
Where in the code we combine them to have a single array for the total field? like _E = np.sum(_E, axis=3) will this be accurate to do ?

**Comment by flaport** [comment]
We never combine them. The three components are independent of each other.
