### ISSUE TITLE
ERROR: File "setup.py" not found.

### ISSUE THREAD

**Issue by mmmmeta** [flaport/fdtd#69]
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: F:\python_fdtd\fdtd
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)

**Comment by flaport** [comment]
Which version of python and which version of pip are you using?

**Comment by mmmmeta** [comment]
python 3.6.15 pip 20.0.2

> Which version of python and which version of pip are you using?

**Comment by flaport** [comment]
your python version is very old. Python 3.6 reached end of life in 2021. Try updating.

**Comment by mmmmeta** [comment]
> your python version is very old. Python 3.6 reached end of life in 2021. Try updating.

I have tried python 3.10 and it works. Thank a lot
