### ISSUE TITLE
Is this an implementation of Convolutional Perfectly Maych Layers

### ISSUE THREAD

**Issue by loliverhennigh** [flaport/fdtd#78]
https://github.com/flaport/fdtd/blob/a0ff3a9891eda5c638061ea785b3a607dda6d0de/fdtd/boundaries.py#L225

Apologies for the naive question but is this an implementation of conventional perfectly matched layers and not the ordinary one? Not an EM expert. Great project!

**Comment by flaport** [comment]
The PML is based on chapter 11 from this book:
https://eecs.wsu.edu/~schneidj/ufdtd
